name: sphinxdocs                     # To make:  conda env create -f *.yml
channels:
  - anaconda
  - conda-forge
dependencies:
  - cloud_sptheme
  - pandoc
  - pbr
  - pip
  - python
  - sphinx
  - sphinx-argparse
  - sphinxcontrib-fulltoc
  - tcsh
  - pip:
    - sphinxcontrib-programoutput
