name: sphinxdocs                  # To make:  conda env create -f *.yml
channel_priority: strict
channels:
  - conda-forge
  - anaconda
dependencies:
  - cloud_sptheme
  - pandoc
  - pbr
  - pip
  - python
  - pandas
  - sphinx
  - sphinx-argparse
  - sphinxcontrib-fulltoc
  - tcsh
  - pip:
    - sphinxcontrib-programoutput
