name: py2_afni_tiny           # TO MAKE:  conda env create -f env*_ex2.yml
dependencies:
  - python=2.7
  - "matplotlib>=2.2.3"       # minimal ver for 'pythonic' APQC HTML
  - numpy
  - scipy
  - pillow
  - ipython
  - flask                     # for local server for APQC HTML 
  - flask-cors                # for local server for APQC HTML 
